name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-tests-lint:

    name: Build & Tests & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Fix gradlew permission
        run: chmod +x gradlew
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
      - name: Assemble → Test → Lint
        run: ./gradlew assembleDebug test lint --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload UnitTest reports
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-reports
          path: |
            **/reports/tests/test*UnitTest/
            **/build/test-results/Test-*.xml
      - name: Upload Lint reports
        uses: actions/upload-artifact@v2
        with:
          name: lint-reports
          path: |
            **/reports/lint-results-*.xml
            **/reports/lint-results-*.html
