name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-tests-lint:

    name: Build & Tests & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./app/google-services.json
      - uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
        with:
          validate-wrappers: true
          gradle-home-cache-cleanup: true
      - name: Assemble → Test → Lint
        run: ./gradlew assembleDebug test lint --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload UnitTest reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-reports
          path: |
            **/reports/tests/test*UnitTest/
            **/build/test-results/Test-*.xml
      - name: Upload Lint reports
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            **/reports/lint-results-*.xml
            **/reports/lint-results-*.html
